ENV = {'PATH': '/usr/local/bin:/opt/bin:/bin:/usr/bin', 'MPICH_CC': 'gcc', 'MPICH_CXX': 'g++', 'LD_LIBRARY_PATH': '', 'MPICH_CLINKER': 'gcc'}
RSFROOT = '/mnt/Archivos/Universidad_de_Antioquia/Proyectos/C3_LINUX/debian_packaging/paquetes/En_Proceso/madagascar/Paquete/madagascar-1.7/debian/madagascar/usr'
AR = 'ar'
JPEG = 'jpeg'
OPENGL = ['GL', 'GLU', 'glut']
OPENGLFLAGS = None
OPENGLPATH = None
MPICC = '/usr/bin/mpicc'
MPICXX = '/usr/bin/mpicxx'
MPIRUN = '/usr/bin/mpirun'
SPARSEPATH = None
SPARSELIBS = None
FFTW = 'fftw3f'
FFTWOMP = 'fftw3f_threads'
OMP = True
PTHREADS = True
BLAS = 'blas'
LAPACK = ['lapack', 'blas']
PPM = None
TIFF = None
GD = None
PLPLOT = None
FFMPEG = None
CAIROPNG = None
SFPEN = 'oglpen'
DYNLIB = ''
CC = 'gcc'
CFLAGS = '-O2 -x c -std=gnu99 -Wall -pedantic -fopenmp'
CPPPATH = []
LIBPATH = []
LIBS = ['m', 'blas', 'lapack', 'blas', 'gomp', 'fftw3f', 'fftw3f_threads']
LINKFLAGS = ['-pthread', '-fopenmp']
XINC = None
API = ['c++']
CXX = 'g++'
CXXFLAGS = '-O2 -Wall -pedantic -fopenmp'
F77 = 'gfortran'
FORTRAN = 'gfortran'
F90 = 'gfortran'
JAVAC = 'javac'
CUDA_TOOLKIT_PATH = None
NUMPY = True
SWIG = None
